<?php
	include_once('php/common.php');	
	 $c = new Cnx();

?>
<html xmlns="http//www.w3.org/1999/xhtml" xmllang="en" lang="en"   ng-app="LoadMap">
<head>
  <title>Easytech.mg</title>
  <script src="js/angular.min.js"></script>
  <meta http-equiv="Content-Type" content="text/html; Charset=utf-8" />
  <meta name="easytech" content="easytech" />
  <meta content="" name="Keywords" />
  <style type="text/css">
    @import url(css/css.css);
  </style>
</head>
<body> <div id="legende"> 

<div class='normal'>Normal</div><br/>
<div class='anomalie'>A verifier</div><br/>
<div class='wrapup'>Sans Lot</div><hr/>

<div class='s1 carre'>OP</div><br/>
<div class='s0 carre'>CADRE</div><br/>
</div>
<div class="titrei">AMPARIBE - 3<sup>éme</sup> ETAGE</div><br>
<div id="afficheur"><img src="img/cl.png" style="float: right; margin-right: 5px;clear: none; position: relative;" onclick="document.getElementById('afficheur').style.display = 'none' ;"><div id="info_details"></div></div>   <center><h1 class='titre'><a href="visu.php">ARO | </a><a href="ARO1.php">ARO 1 | </a><a href="ARO2.php">ARO 2 | </a><a href="AlmerysAmparibe_visu.php">AMPARIBE | </a><a href="Amparibe-sou-sol_visu.php">RDJ </a></h1>
<div data-ng-controller="simpleController">      
<table class='plan_site'>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'></td></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='table' id='248'><?php echo $c->echoS('s248s'); ?></td><td class='table' id='249'><?php echo $c->echoS('s249s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='250'><?php echo $c->echoS('s250s'); ?></td><td class='table' id='251'><?php echo $c->echoS('s251s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='252'><?php echo $c->echoS('s252s'); ?></td><td class='table' id='253'><?php echo $c->echoS('s253s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='254'><?php echo $c->echoS('s254s'); ?></td><td class='table' id='255'><?php echo $c->echoS('s255s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='256'><?php echo $c->echoS('s256s'); ?></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='table' id='257'><?php echo $c->echoS('s257s'); ?></td><td class='table' id='258'><?php echo $c->echoS('s258s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='259'><?php echo $c->echoS('s259s'); ?></td><td class='table' id='260'><?php echo $c->echoS('s260s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='261'><?php echo $c->echoS('s261s'); ?></td><td class='table' id='262'><?php echo $c->echoS('s262s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='263'><?php echo $c->echoS('s263s'); ?></td><td class='table' id='264'><?php echo $c->echoS('s264s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='265'><?php echo $c->echoS('s265s'); ?></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='table' id='266'><?php echo $c->echoS('s266s'); ?></td><td class='table' id='267'><?php echo $c->echoS('s267s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='268'><?php echo $c->echoS('s268s'); ?></td><td class='table' id='269'><?php echo $c->echoS('s269s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='270'><?php echo $c->echoS('s270s'); ?></td><td class='table' id='271'><?php echo $c->echoS('s271s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='272'><?php echo $c->echoS('s272s'); ?></td><td class='table' id='273'><?php echo $c->echoS('s273s'); ?></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='274'><?php echo $c->echoS('s274s'); ?></td><td class='table' id='275'><?php echo $c->echoS('s275s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='276'><?php echo $c->echoS('s276s'); ?></td><td class='table' id='277'><?php echo $c->echoS('s277s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='278'><?php echo $c->echoS('s278s'); ?></td><td class='table' id='279'><?php echo $c->echoS('s279s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='280'><?php echo $c->echoS('s280s'); ?></td><td class='table' id='281'><?php echo $c->echoS('s281s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='282'><?php echo $c->echoS('s282s'); ?></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='table' id='283'><?php echo $c->echoS('s283s'); ?></td><td class='table' id='284'><?php echo $c->echoS('s284s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='285'><?php echo $c->echoS('s285s'); ?></td><td class='table' id='286'><?php echo $c->echoS('s286s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='287'><?php echo $c->echoS('s287s'); ?></td><td class='table' id='288'><?php echo $c->echoS('s288s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='289'><?php echo $c->echoS('s289s'); ?></td><td class='table' id='290'><?php echo $c->echoS('s290s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='291'><?php echo $c->echoS('s291s'); ?></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='292'><?php echo $c->echoS('s292s'); ?></td><td class='table' id='293'><?php echo $c->echoS('s293s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='294'><?php echo $c->echoS('s294s'); ?></td><td class='table' id='295'><?php echo $c->echoS('s295s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='296'><?php echo $c->echoS('s296s'); ?></td><td class='table' id='297'><?php echo $c->echoS('s297s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='298'><?php echo $c->echoS('s298s'); ?></td><td class='table' id='299'><?php echo $c->echoS('s299s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='300'><?php echo $c->echoS('s300s'); ?></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='table' id='301'><?php echo $c->echoS('s301s'); ?></td><td class='table' id='302'><?php echo $c->echoS('s302s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='303'><?php echo $c->echoS('s303s'); ?></td><td class='table' id='304'><?php echo $c->echoS('s304s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='305'><?php echo $c->echoS('s305s'); ?></td><td class='table' id='306'><?php echo $c->echoS('s306s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='307'><?php echo $c->echoS('s307s'); ?></td><td class='table' id='308'><?php echo $c->echoS('s308s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='309'><?php echo $c->echoS('s309s'); ?></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='310'><?php echo $c->echoS('s310s'); ?></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='table' id='311'><?php echo $c->echoS('s311s'); ?></td><td class='table' id='312'><?php echo $c->echoS('s312s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='313'><?php echo $c->echoS('s313s'); ?></td><td class='table' id='314'><?php echo $c->echoS('s314s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='315'><?php echo $c->echoS('s315s'); ?></td><td class='table' id='316'><?php echo $c->echoS('s316s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='317'><?php echo $c->echoS('s317s'); ?></td><td class='table' id='318'><?php echo $c->echoS('s318s'); ?></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='table' id='319'><?php echo $c->echoS('s319s'); ?></td><td class='allee'></td><td class='table' id='320'><?php echo $c->echoS('s320s'); ?></td><td class='allee'></td><td class='table' id='321'><?php echo $c->echoS('s321s'); ?></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='table' id='322'><?php echo $c->echoS('s322s'); ?></td><td class='table' id='323'><?php echo $c->echoS('s323s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='324'><?php echo $c->echoS('s324s'); ?></td><td class='table' id='325'><?php echo $c->echoS('s325s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='326'><?php echo $c->echoS('s326s'); ?></td><td class='table' id='327'><?php echo $c->echoS('s327s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='328'><?php echo $c->echoS('s328s'); ?></td><td class='table' id='329'><?php echo $c->echoS('s329s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='330'><?php echo $c->echoS('s330s'); ?></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='table' id='331'><?php echo $c->echoS('s331s'); ?></td><td class='table' id='332'><?php echo $c->echoS('s332s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='333'><?php echo $c->echoS('s333s'); ?></td><td class='table' id='334'><?php echo $c->echoS('s334s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='335'><?php echo $c->echoS('s335s'); ?></td><td class='table' id='336'><td class='allee'></td><td class='allee'><td class='table' id='337'><?php echo $c->echoS('s337s'); ?></td><td class='table' id='338'><?php echo $c->echoS('s338s'); ?></td><td class='allee'></td><td class='allee'><td class='table' id='339'><?php echo $c->echoS('s339s'); ?></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='table' id='340'><?php echo $c->echoS('s340s'); ?></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='table' id='341'><?php echo $c->echoS('s341s'); ?></td><td class='table' id='342'><?php echo $c->echoS('s342s'); ?></td><td class='table' id='343'><?php echo $c->echoS('s343s'); ?></td><td class='table' id='344'><?php echo $c->echoS('s344s'); ?></td><td class='table' id='345'><?php echo $c->echoS('s345s'); ?></td><td class='table' id='346'><?php echo $c->echoS('s346s'); ?></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'></td></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td></tr>
</table>   
</center> 

</div>
<script type="text/javascript">

var app = angular.module('LoadMap', []);

app.controller('simpleController', function($scope, $http) {
	getTask(); // Load all available tasks 
var timer = setInterval(function getTask(){  
	$http.post("getTask.php").success(function(data){
		$scope.gpao = data;
	   });
	}, 60000);  
	
	function getTask(){  
	$http.post("getTask.php").success(function(data){
		$scope.gpao = data;
	   });
	};
	
  });
</script>

</body>
</html>

