<?php
	include_once('php/common.php');	
	 $c = new Cnx();
	 //return;
?>
<html xmlns="http//www.w3.org/1999/xhtml" xmllang="en" lang="en">
<head>
  <title>Easytech.mg</title>
  <meta http-equiv="Content-Type" content="text/html; Charset=utf-8" />
  <meta name="easytech" content="easytech" />
  <meta content="" name="Keywords" />
  <style type="text/css">
    @import url(css/css.css);
  </style>
</head>
<body> <div id="afficheur"><img src="img/cl.png" style="float: right; margin-right: 5px;clear: none; position: relative;" onclick="document.getElementById('afficheur').style.display = 'none' ;"><div id="info_details"></div></div>   <center><h1 class='titre'>PLAN Almerys AMPARIBE</h1>     
<table class='plan_site'>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'></td></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='table' id='248'></td><td class='table' id='249'></td><td class='allee'></td><td class='allee'><td class='table' id='250'></td><td class='table' id='251'></td><td class='allee'></td><td class='allee'><td class='table' id='252'></td><td class='table' id='253'><td class='allee'></td><td class='allee'><td class='table' id='254'></td><td class='table' id='255'></td><td class='allee'></td><td class='allee'><td class='table' id='256'></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='table' id='257'></td><td class='table' id='258'></td><td class='allee'></td><td class='allee'><td class='table' id='259'></td><td class='table' id='260'></td><td class='allee'></td><td class='allee'><td class='table' id='261'></td><td class='table' id='262'><td class='allee'></td><td class='allee'><td class='table' id='263'></td><td class='table' id='264'></td><td class='allee'></td><td class='allee'><td class='table' id='265'></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='table' id='266'></td><td class='table' id='267'></td><td class='allee'></td><td class='allee'><td class='table' id='268'></td><td class='table' id='269'></td><td class='allee'></td><td class='allee'><td class='table' id='270'></td><td class='table' id='271'><td class='allee'></td><td class='allee'><td class='table' id='272'></td><td class='table' id='273'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='274'></td><td class='table' id='275'></td><td class='allee'></td><td class='allee'><td class='table' id='276'></td><td class='table' id='277'></td><td class='allee'></td><td class='allee'><td class='table' id='278'></td><td class='table' id='279'><td class='allee'></td><td class='allee'><td class='table' id='280'></td><td class='table' id='281'></td><td class='allee'></td><td class='allee'><td class='table' id='282'></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='table' id='283'></td><td class='table' id='284'></td><td class='allee'></td><td class='allee'><td class='table' id='285'></td><td class='table' id='286'></td><td class='allee'></td><td class='allee'><td class='table' id='287'></td><td class='table' id='288'><td class='allee'></td><td class='allee'><td class='table' id='289'></td><td class='table' id='290'></td><td class='allee'></td><td class='allee'><td class='table' id='291'></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='292'></td><td class='table' id='293'></td><td class='allee'></td><td class='allee'><td class='table' id='294'></td><td class='table' id='295'></td><td class='allee'></td><td class='allee'><td class='table' id='296'></td><td class='table' id='297'><td class='allee'></td><td class='allee'><td class='table' id='298'></td><td class='table' id='299'></td><td class='allee'></td><td class='allee'><td class='table' id='300'></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='table' id='301'></td><td class='table' id='302'></td><td class='allee'></td><td class='allee'><td class='table' id='303'></td><td class='table' id='304'></td><td class='allee'></td><td class='allee'><td class='table' id='305'></td><td class='table' id='306'><td class='allee'></td><td class='allee'><td class='table' id='307'></td><td class='table' id='308'></td><td class='allee'></td><td class='allee'><td class='table' id='309'></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='310'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='table' id='311'></td><td class='table' id='312'></td><td class='allee'></td><td class='allee'><td class='table' id='313'></td><td class='table' id='314'></td><td class='allee'></td><td class='allee'><td class='table' id='315'></td><td class='table' id='316'><td class='allee'></td><td class='allee'><td class='table' id='317'></td><td class='table' id='318'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='table' id='319'></td><td class='allee'></td><td class='table' id='320'></td><td class='allee'></td><td class='table' id='321'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='table' id='322'></td><td class='table' id='323'></td><td class='allee'></td><td class='allee'><td class='table' id='324'></td><td class='table' id='325'></td><td class='allee'></td><td class='allee'><td class='table' id='326'></td><td class='table' id='327'><td class='allee'></td><td class='allee'><td class='table' id='328'></td><td class='table' id='329'></td><td class='allee'></td><td class='allee'><td class='table' id='330'></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='table' id='331'></td><td class='table' id='332'></td><td class='allee'></td><td class='allee'><td class='table' id='333'></td><td class='table' id='334'></td><td class='allee'></td><td class='allee'><td class='table' id='335'></td><td class='table' id='336'><td class='allee'></td><td class='allee'><td class='table' id='337'></td><td class='table' id='338'></td><td class='allee'></td><td class='allee'><td class='table' id='339'></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='table' id='340'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='table' id='341'></td><td class='table' id='342'></td><td class='table' id='343'></td><td class='table' id='344'></td><td class='table' id='345'></td><td class='table' id='346'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'><td class='allee'></td><td class='allee'></td></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'><td class='wall_'></td><td class='wall_'></td></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td></tr>
</table>   
</body>
<script language="javascript" type="text/javascript" src="js/jquery.js"></script>
<script language="javascript" type="text/javascript" charset="utf-8">
$('td').click(function(){
	var id = $(this).attr('id');
		if (id != undefined) 
		{
			$("#"+id).html('<div class="body" id="Etape"><img src = "img/ramiLoad.gif" width="30px"/>Loading ...</div>');

			$.ajax({
				type: "POST",
				url: "php/link.php?action=saveMac&id="+$(this).attr('id'),
					success: function(msg){
						//alert($(this).html());
						$("#"+id).html("<td>"+msg+"</td>");
					},
				});
		}
	});
	
	</script>
</html>

