<?php
	include_once('php/common.php');	
	 $c = new Cnx();
	 //return;
?>
<html xmlns="http//www.w3.org/1999/xhtml" xmllang="en" lang="en">
<head>
  <title>Easytech.mg</title>
  <meta http-equiv="Content-Type" content="text/html; Charset=utf-8" />
  <meta name="easytech" content="easytech" />
  <meta content="" name="Keywords" />
  <style type="text/css">
    @import url(css/css.css);
  </style>
</head>
<body> <div id="afficheur"><img src="img/cl.png" style="float: right; margin-right: 5px;clear: none; position: relative;" onclick="document.getElementById('afficheur').style.display = 'none' ;"><div id="info_details"></div></div>   <center><h1 class='titre'>PLAN ARO-1</h1>     
<table class='plan_site'>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='0'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='empty'></td><td class='empty'></td><td class='empty'></td><td class='empty'></td><td class='empty'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='1'></td><td class='uc' id='2'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='3'></td><td class='uc' id='4'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='5'></td><td class='uc' id='6'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='uc' id='7'></td><td class='uc' id='8'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='9'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='empty'></td><td class='empty'></td><td class='empty'></td><td class='empty'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='10'></td><td class='uc' id='11'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='12'></td><td class='uc' id='13'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='14'></td><td class='uc' id='15'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='16'></td><td class='uc' id='17'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='18'></td><td class='uc' id='19'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='20'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='empty'></td><td class='empty'></td><td class='empty'></td><td class='empty'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='21'></td><td class='uc' id='22'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='23'></td><td class='uc' id='24'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='25'></td><td class='uc' id='26'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='27'></td><td class='uc' id='28'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='29'></td><td class='uc' id='30'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='31'></td><td class='uc' id='32'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='empty'></td><td class='empty'></td><td class='empty'></td><td class='empty'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='33'></td><td class='uc' id='34'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='35'></td><td class='uc' id='36'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='37'></td><td class='uc' id='38'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='39'></td><td class='uc' id='40'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='41'></td><td class='uc' id='42'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='43'></td><td class='uc' id='44'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='45'></td><td class='uc' id='46'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='empty'></td><td class='empty'></td><td class='empty'></td><td class='empty'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='47'></td><td class='uc' id='48'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='49'></td><td class='uc' id='50'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='51'></td><td class='uc' id='52'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='53'></td><td class='uc' id='54'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='55'></td><td class='uc' id='56'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='57'></td><td class='uc' id='58'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='59'></td><td class='uc' id='60'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='61'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='empty'></td><td class='empty'></td><td class='empty'></td><td class='empty'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='62'></td><td class='uc' id='63'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='64'></td><td class='uc' id='65'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='66'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='empty'></td><td class='empty'></td><td class='empty'></td><td class='empty'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='67'></td><td class='uc' id='68'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='69'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='empty'></td><td class='empty'></td><td class='empty'></td><td class='empty'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='70'></td><td class='uc' id='71'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='72'></td><td class='uc' id='73'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='74'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='75'></td><td class='uc' id='76'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='77'></td><td class='uc' id='78'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='79'></td><td class='uc' id='80'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='81'></td><td class='uc' id='82'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='83'></td><td class='uc' id='84'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='85'></td><td class='uc' id='86'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='87'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='88'></td><td class='uc' id='89'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='90'></td><td class='uc' id='91'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='92'></td><td class='uc' id='93'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='94'></td><td class='uc' id='95'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='96'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='97'></td><td class='uc' id='98'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='99'></td><td class='uc' id='100'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='101'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='102'></td><td class='uc' id='103'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='104'></td><td class='uc' id='105'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='106'></td><td class='uc' id='107'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='108'></td><td class='uc' id='109'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td></tr>
</table>   
</center> </body>
<script language="javascript" type="text/javascript" src="js/jquery.js"></script>
<script language="javascript" type="text/javascript" charset="utf-8">
window.onload=function() {
	//timer = setInterval('blink()', 500);
}
setInterval(function () {
  var vis = $(".anomalie").css("visibility");
  vis = (!vis || vis == "visible") ? "hidden" : "visible";
  $(".anomalie").css("visibility", vis);
}, 500);
	
	
	$('td').each(function () {
			if ($(this).attr('id') != undefined) {
				$.ajax({
					type: "POST",
					url: "php/link.php?action=getStatut&ip="+$(this).attr('id'),
						success: function(msg){
							elem= msg;
							//alert('msg');
							if (elem == '') elem = $(this).attr('id');
						},async:  false
					});
					//if ($(this).attr('id') != '222222222222')
					//$(this).html($(this).attr('id'));	
					$(this).html(elem);					
			}
			//else $(this).html('elem');	
		});
	
	$('td').click(function(){
	var id = $(this).attr('id');
		if (id != undefined) 
		{
			$("#"+id).html('<div class="body" id="Etape"><img src = "img/ramiLoad.gif" width="30px"/>Loading ...</div>');
		
			$.ajax({
				type: "POST",
				url: "php/link.php?action=saveMac&id="+$(this).attr('id'),
					success: function(msg){
						alert($(this).html());
						$("#"+id).html("<td>"+msg+"</td>");
					},
				});
		}
	});
	
</script>
</html>

