<?php

	include_once('php/common.php');	
	 $c = new Cnx();

?>
<html xmlns="http//www.w3.org/1999/xhtml" xmllang="en" lang="en"   ng-app="LoadMap">
<head>
  <title>Easytech.mg</title>
  <script src="js/angular.min.js"></script>
  <meta http-equiv="Content-Type" content="text/html; Charset=utf-8" />
  <meta name="easytech" content="easytech" />
  <meta content="" name="Keywords" />
  <style type="text/css">
    @import url(css/css.css);
  </style>
</head>
<body>  <div id="legende"> 

<div class='normal'>Normal</div><br/>
<div class='anomalie'>A verifier</div><br/>
<div class='wrapup'>Sans Lot</div><hr/>

<div class='s1 carre'>OP</div><br/>
<div class='s0 carre'>CADRE</div><br/>
</div>

<div class="titrei">ARO AILE DROITE</div>

<div id="afficheur"><img src="img/cl.png" style="float: right; margin-right: 5px;clear: none; position: relative;" onclick="document.getElementById('afficheur').style.display = 'none' ;"><div id="info_details"></div></div>   <center><h1 class='titre'><a href="visu.php">ARO | </a><a href="ARO1.php">ARO 1 | </a><a href="ARO2.php">ARO 2 | </a><a href="AlmerysAmparibe_visu.php">AMPARIBE | </a><a href="Amparibe-sou-sol_visu.php">RDJ </a></h1>
<div data-ng-controller="simpleController">      
<table class='plan_site'>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='0'><?php echo $c->echoS('s0s'); ?></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='table' id='1'><?php echo $c->echoS('s1s'); ?></td><td class='table' id='2'><?php echo $c->echoS('s2s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='3'><?php echo $c->echoS('s3s'); ?></td><td class='table' id='4'><?php echo $c->echoS('s4s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='5'><?php echo $c->echoS('s5s'); ?></td><td class='table' id='6'><?php echo $c->echoS('s6s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='table' id='7'><?php echo $c->echoS('s7s'); ?></td><td class='table' id='8'><?php echo $c->echoS('s8s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='9'><?php echo $c->echoS('s9s'); ?></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='table' id='10'><?php echo $c->echoS('s10s'); ?></td><td class='table' id='11'><?php echo $c->echoS('s11s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='12'><?php echo $c->echoS('s12s'); ?></td><td class='table' id='13'><?php echo $c->echoS('s13s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='14'><?php echo $c->echoS('s14s'); ?></td><td class='table' id='15'><?php echo $c->echoS('s15s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='16'><?php echo $c->echoS('s16s'); ?></td><td class='table' id='17'><?php echo $c->echoS('s17s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='18'><?php echo $c->echoS('s18s'); ?></td><td class='table' id='19'><?php echo $c->echoS('s19s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='20'><?php echo $c->echoS('s20s'); ?></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='table' id='21'><?php echo $c->echoS('s21s'); ?></td><td class='table' id='22'><?php echo $c->echoS('s22s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='23'><?php echo $c->echoS('s23s'); ?></td><td class='table' id='24'><?php echo $c->echoS('s24s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='25'><?php echo $c->echoS('s25s'); ?></td><td class='table' id='26'><?php echo $c->echoS('s26s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='27'><?php echo $c->echoS('s27s'); ?></td><td class='table' id='28'><?php echo $c->echoS('s28s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='29'><?php echo $c->echoS('s29s'); ?></td><td class='table' id='30'><?php echo $c->echoS('s30s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='table' id='31'><?php echo $c->echoS('s31s'); ?></td><td class='table' id='32'><?php echo $c->echoS('s32s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='table' id='33'><?php echo $c->echoS('s33s'); ?></td><td class='table' id='34'><?php echo $c->echoS('s34s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='35'><?php echo $c->echoS('s35s'); ?></td><td class='table' id='36'><?php echo $c->echoS('s36s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='37'><?php echo $c->echoS('s37s'); ?></td><td class='table' id='38'><?php echo $c->echoS('s38s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='39'><?php echo $c->echoS('s39s'); ?></td><td class='table' id='40'><?php echo $c->echoS('s40s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='41'><?php echo $c->echoS('s41s'); ?></td><td class='table' id='42'><?php echo $c->echoS('s42s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='43'><?php echo $c->echoS('s43s'); ?></td><td class='table' id='44'><?php echo $c->echoS('s44s'); ?></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='table' id='45'><?php echo $c->echoS('s45s'); ?></td><td class='table' id='46'><?php echo $c->echoS('s46s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='table' id='47'><?php echo $c->echoS('s47s'); ?></td><td class='table' id='48'><?php echo $c->echoS('s48s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='49'><?php echo $c->echoS('s49s'); ?></td><td class='table' id='50'><?php echo $c->echoS('s50s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='51'><?php echo $c->echoS('s51s'); ?></td><td class='table' id='52'><?php echo $c->echoS('s52s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='53'><?php echo $c->echoS('s53s'); ?></td><td class='table' id='54'><?php echo $c->echoS('s54s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='55'><?php echo $c->echoS('s55s'); ?></td><td class='table' id='56'><?php echo $c->echoS('s56s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='57'><?php echo $c->echoS('s57s'); ?></td><td class='table' id='58'><?php echo $c->echoS('s58s'); ?></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='table' id='59'><?php echo $c->echoS('s59s'); ?></td><td class='table' id='60'><?php echo $c->echoS('s60s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='61'><?php echo $c->echoS('s61s'); ?></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='62'><?php echo $c->echoS('s62s'); ?></td><td class='table' id='63'><?php echo $c->echoS('s63s'); ?></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='table' id='64'><?php echo $c->echoS('s64s'); ?></td><td class='table' id='65'><?php echo $c->echoS('s65s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='66'><?php echo $c->echoS('s66s'); ?></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='table' id='67'><?php echo $c->echoS('s67s'); ?></td><td class='table' id='68'><?php echo $c->echoS('s68s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='69'><?php echo $c->echoS('s69s'); ?></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='table' id='70'><?php echo $c->echoS('s70s'); ?></td><td class='table' id='71'><?php echo $c->echoS('s71s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='72'><?php echo $c->echoS('s72s'); ?></td><td class='table' id='73'><?php echo $c->echoS('s73s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='74'><?php echo $c->echoS('s74s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='75'><?php echo $c->echoS('s75s'); ?></td><td class='table' id='76'><?php echo $c->echoS('s76s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='77'><?php echo $c->echoS('s77s'); ?></td><td class='table' id='78'><?php echo $c->echoS('s78s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='79'><?php echo $c->echoS('s79s'); ?></td><td class='table' id='80'><?php echo $c->echoS('s80s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='81'><?php echo $c->echoS('s81s'); ?></td><td class='table' id='82'><?php echo $c->echoS('s82s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='table' id='83'><?php echo $c->echoS('s83s'); ?></td><td class='table' id='84'><?php echo $c->echoS('s84s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='85'><?php echo $c->echoS('s85s'); ?></td><td class='table' id='86'><?php echo $c->echoS('s86s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='87'><?php echo $c->echoS('s87s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='88'><?php echo $c->echoS('s88s'); ?></td><td class='table' id='89'><?php echo $c->echoS('s89s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='90'><?php echo $c->echoS('s90s'); ?></td><td class='table' id='91'><?php echo $c->echoS('s91s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='92'><?php echo $c->echoS('s92s'); ?></td><td class='table' id='93'><?php echo $c->echoS('s93s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='94'><?php echo $c->echoS('s94s'); ?></td><td class='table' id='95'><?php echo $c->echoS('s95s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='96'><?php echo $c->echoS('s96s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td></tr>
<tr class='range'><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='table' id='97'><?php echo $c->echoS('s97s'); ?></td><td class='table' id='98'><?php echo $c->echoS('s98s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='99'><?php echo $c->echoS('s99s'); ?></td><td class='table' id='100'><?php echo $c->echoS('s100s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='table' id='101'><?php echo $c->echoS('s101s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='102'><?php echo $c->echoS('s102s'); ?></td><td class='table' id='103'><?php echo $c->echoS('s103s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='104'><?php echo $c->echoS('s104s'); ?></td><td class='table' id='105'><?php echo $c->echoS('s105s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='106'><?php echo $c->echoS('s106s'); ?></td><td class='table' id='107'><?php echo $c->echoS('s107s'); ?></td><td class='allee'></td><td class='allee'></td><td class='table' id='108'><?php echo $c->echoS('s108s'); ?></td><td class='table' id='109'><?php echo $c->echoS('s109s'); ?></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td></tr>
</table>   
</center> 

</div>
<script type="text/javascript">

var app = angular.module('LoadMap', []);

app.controller('simpleController', function($scope, $http) {
	getTask(); // Load all available tasks 
var timer = setInterval(function getTask(){  
	$http.post("getTask.php").success(function(data){
		$scope.gpao = data;
	   });
	}, 60000);  
	
	function getTask(){  
	$http.post("getTask.php").success(function(data){
		$scope.gpao = data;
	   });
	};
	
  });
</script>

</body>
</html>