<?php
	include_once('php/common.php');	
	 $c = new Cnx();
	 //return;
?>
<html xmlns="http//www.w3.org/1999/xhtml" xmllang="en" lang="en">
<head>
  <title>Easytech.mg</title>
  <meta http-equiv="Content-Type" content="text/html; Charset=utf-8" />
  <meta name="easytech" content="easytech" />
  <meta content="" name="Keywords" />
  <style type="text/css">
    @import url(css/css.css);
  </style>
</head>
<body> <div id="afficheur"><img src="img/cl.png" style="float: right; margin-right: 5px;clear: none; position: relative;" onclick="document.getElementById('afficheur').style.display = 'none' ;"><div id="info_details"></div></div>   <center><h1 class='titre'>PLAN ARO-2</h1>     
<table class='plan_site'>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='247'></td><td class='uc' id='110'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='111'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='112'></td><td class='uc' id='113'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='114'></td><td class='uc' id='115'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='116'></td><td class='uc' id='117'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='118'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='245'></td><td class='uc' id='119'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='120'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='121'></td><td class='uc' id='122'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='123'></td><td class='uc' id='124'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='125'></td><td class='uc' id='126'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='127'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='246'></td><td class='uc' id='128'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='129'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='130'></td><td class='uc' id='131'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='132'></td><td class='uc' id='133'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='134'></td><td class='uc' id='135'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='136'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='wall_'></td></tr>   
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='137'></td><td class='uc' id='138'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='139'></td><td class='uc' id='140'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='141'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='142'></td><td class='uc' id='143'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='144'></td><td class='uc' id='145'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='146'></td><td class='uc' id='147'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='148'></td><td class='uc' id='149'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='150'></td><td class='uc' id='151'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='152'></td><td class='uc' id='153'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='154'></td><td class='uc' id='155'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='156'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='157'></td><td class='uc' id='158'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='159'></td><td class='uc' id='160'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='161'></td><td class='uc' id='162'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='163'></td><td class='uc' id='164'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='165'></td><td class='uc' id='166'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='167'></td><td class='uc' id='168'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='169'></td><td class='uc' id='170'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='171'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='172'></td><td class='uc' id='173'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='174'></td><td class='uc' id='175'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='176'></td><td class='uc' id='177'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='178'></td><td class='uc' id='179'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='180'></td><td class='uc' id='181'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='uc' id='182'></td><td class='uc' id='183'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='184'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>     
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='185'></td><td class='uc' id='186'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='187'></td><td class='uc' id='188'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='189'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='190'></td><td class='uc' id='191'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='192'></td><td class='uc' id='193'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='194'></td><td class='uc' id='195'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='196'></td><td class='uc' id='197'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='198'></td><td class='uc' id='199'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='uc' id='200'></td><td class='uc' id='201'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='202'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>     
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='203'></td><td class='uc' id='204'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='205'></td><td class='uc' id='206'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='207'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='208'></td><td class='uc' id='209'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='210'></td><td class='uc' id='211'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='212'></td><td class='uc' id='213'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='214'></td><td class='uc' id='215'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='216'></td><td class='uc' id='217'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='uc' id='218'></td><td class='uc' id='219'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='220'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>     
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td><td class='allee'></td><td class='uc' id='221'></td><td class='uc' id='222'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='uc' id='223'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='allee'></td><td class='wall_'></td></tr>     
<tr class='range'><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td><td class='wall_'></td></tr>
</table>   
</center> </body>
<script language="javascript" type="text/javascript" src="js/jquery.js"></script>
<script language="javascript" type="text/javascript" charset="utf-8">
window.onload=function() {
	//timer = setInterval('blink()', 500);
}
setInterval(function () {
  var vis = $(".anomalie").css("visibility");
  vis = (!vis || vis == "visible") ? "hidden" : "visible";
  $(".anomalie").css("visibility", vis);
}, 500);
	
	/*
	$('td').each(function () {
			if ($(this).attr('id') != undefined) {
				$.ajax({
					type: "POST",
					url: "php/link.php?action=getStatut&ip="+$(this).attr('id'),
						success: function(msg){
							elem= msg;
							//alert('msg');
							if (elem == '') elem = $(this).attr('id');
						},async:  false
					});
					//if ($(this).attr('id') != '222222222222')
					//$(this).html($(this).attr('id'));	
					$(this).html(elem);					
			}
			//else $(this).html('elem');	
		});
	*/
	$('td').click(function(){
	var id = $(this).attr('id');
		if (id != undefined) 
		{
			$("#"+id).html('<div class="body" id="Etape"><img src = "img/ramiLoad.gif" width="30px"/>Loading ...</div>');
		
			$.ajax({
				type: "POST",
				url: "php/link.php?action=saveMac&id="+$(this).attr('id'),
					success: function(msg){
						//alert($(this).html());
						$("#"+id).html("<td>"+msg+"</td>");
					},
				});
		}
	});
	
</script>
</html>

